name: savetaxindia
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  assorted_layout_widgets: ^11.0.0
  cloud_firestore: ^5.0.0
  connectivity_plus: ^6.0.2
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  file_picker: ^10.1.9
  firebase_app_check: ^0.3.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.2
  fluttertoast: ^8.2.1
  flutter_screenutil: ^5.7.0
  get: ^4.6.5
  get_it: ^8.0.0
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  google_sign_in: ^7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  meta: ^1.8.0
  intl: ^0.20.2
  percent_indicator: ^4.2.3
  permission_handler: ^12.0.0+1
  pinput: ^5.0.0
  provider: ^6.1.5
  scratcher: ^2.3.0
  uuid: ^4.0.0
  url_launcher: ^6.3.1
  smart_auth: ^3.0.0
  share_plus: ^11.0.0
  dotted_border: ^3.0.1
  image_picker: ^1.1.2
  objectbox: ^4.3.0
  firebase_storage: ^12.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  test: ^1.24.9
  network_image_mock: ^2.1.1
  fake_cloud_firestore: ^2.4.8
  firebase_auth_mocks: ^0.14.0
  firebase_core_platform_interface: ^5.0.0
  firebase_auth_platform_interface: ^7.0.0

flutter:
  uses-material-design: true

  assets: 
   - .env
   - assets/images/
   - assets/icons/